/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_AShell_CallSystem */

#ifndef _Included_com_example_AShell_CallSystem
#define _Included_com_example_AShell_CallSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_AShell_CallSystem
 * Method:    System
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_AShell_CallSystem_System
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_AShell_CallSystem
 * Method:    chdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_AShell_CallSystem_chdir
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
